### ISSUE TITLE
D-Link DWA-131 Wireless N Nano USB Adapter (Black) Not working in macOS Catalina

### ISSUE THREAD

**Issue by blackviper007** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#5]
Hi, is your D-Link DWA-131 Wireless N Nano USB Adapter (Black) work in macOS Catalina? If yes can you provide the files thanks

**Comment by gajjartejas** [comment]
Sorry, I can't test because I broke my D-Link DWA-131 while traveling with it. I don't know that it was attached to USB port:(

Some suggestions:
WiFi is a headache. Recently I have brought Dell DW1820A wireless M.2 adaptor from AliExpress but sadly not properly working with Mojave. Generally, DW1820A is 3 types of card available. I choose the wrong part no, which is not working properly. There is kernel panic with it. If you really want to buy just buy the 0VW3T3 part. Pro tip doesn't buy it from AliExpress thy will always sent incorrect part no. More guide is here: https://osxlatitude.com/forums/topic/11322-broadcom-bcm4350-cards-under-high-sierramojave/

There are other cards available but it is expensive.

DW1560 (BCM94352Z- 867Mbps - BT4.0, pricier, I don't see why would you go with this card if the above is cheaper)

DW1830 (BCM94360 - 1300Mbps - BT4.0, priciest, needs 3 antennas to work to its full potential, works with just 2 tho, LARGE footprint, and I don't think it would fit there)
